---
version: "2"
plugins:
  duplication:
    enabled: true
    config:
      languages:
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: false
  sonar-php:
    enabled: false
    config:
      tests_patterns:
        - src/tests/**
exclude_patterns:
  - ".idea/**/*"
  - "build/**/*"
  - "docs/**/*"
  - "tests/**/*"
  - "vendor/**/*"
  - "test*.php"
