dist: xenial
language: php

matrix:
  fast_finish: true
  include:
    - php: "7.0"
      env: REPORT=true
      git:
        depth: false
      addons:
        sonarcloud:
          organization: "kreait"
    - php: "7.1"
    - php: "7.2"
    - php: "7.3"

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - |
    if [ "$TRAVIS_SECURE_ENV_VARS" = "true" ]; then
      openssl aes-256-cbc -K $encrypted_d51fa485ef84_key -iv $encrypted_d51fa485ef84_iv -in secrets.tar.enc -out secrets.tar -d;
      tar xvf secrets.tar
    fi

install:
  - composer update --no-interaction --no-suggest --no-progress

script:
  - vendor/bin/phpstan analyse src -c phpstan.neon --level=max --no-progress
  - |
    if [ "$REPORT" = "true" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
      vendor/bin/phpunit --coverage-clover=coverage-report.clover --log-junit=test-report.xml
      sonar-scanner
    else
      vendor/bin/phpunit --testsuite unit
    fi
