language: php

env:
  global:
    - UNIT_TESTS=0
    - STATIC_ANALYSIS=0
    - INTEGRATION_TESTS=0
    - CODE_COVERAGE=0

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: UNIT_TESTS=1
    - php: 7.1
      env: UNIT_TESTS=1 COMPOSER_FLAGS=--ignore-platform-reqs
    - php: 7.2
      env: UNIT_TESTS=1 COMPOSER_FLAGS=--ignore-platform-reqs
    - php: 7.2
      env: STATIC_ANALYSIS=1 COMPOSER_FLAGS=--ignore-platform-reqs
    - php: 7.2
      env: INTEGRATION_TESTS=1 COMPOSER_FLAGS=--ignore-platform-reqs
    - php: 7.2
      env: CODE_COVERAGE=1 COMPOSER_FLAGS=--ignore-platform-reqs
  allow_failures:
    - php: 7.2
      env: CODE_COVERAGE=1 COMPOSER_FLAGS=--ignore-platform-reqs

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install: .travis/before_install.sh

install: .travis/install.sh

script: .travis/build.sh

notifications:
  email:
    - secure: "iiseqb4k4ckQkMJnZ6Tq3YP5ilTZE4CkVgarsBpPOn+c820nP9QokGpz82D4CTGy/UB1+DfCiFH9YAFrhLP5/9Go1CHP+wYkuz9W+E8q/rm9/nBO0xutoQhOfV3MxMid69E8i4QjODq3w5mOUrmpj/8gl2FyBU1Ro1xgPSYNEQ4="
