language: php

env:
  global:
    - UNIT_TESTS=1
    - STATIC_ANALYSIS=0
    - INTEGRATION_TESTS=0
    - CODE_COVERAGE=0
    - DEFAULT_COMPOSER_FLAGS='--profile --ansi --prefer-dist --no-interaction --optimize-autoloader --no-suggest --no-progress'
    - PHPUNIT_FLAGS='--testsuite unit'
    - CC_TEST_REPORTER_ID=6e569def80067b8098353f7391c0c478f024666d7227ce7b89b2a7112805d2bd

matrix:
  fast_finish: true
  include:
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.2
      env: STATIC_ANALYSIS=1
    - php: 7.2
      env: PHPUNIT_FLAGS='--testsuite integration'
    - php: 7.2
      env: CODE_COVERAGE=1
  allow_failures:
    - php: 7.2
      env: CODE_COVERAGE=1

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install: .travis/before_install.sh

install: .travis/install.sh

script: .travis/build.sh

notifications:
  email:
    - secure: "iiseqb4k4ckQkMJnZ6Tq3YP5ilTZE4CkVgarsBpPOn+c820nP9QokGpz82D4CTGy/UB1+DfCiFH9YAFrhLP5/9Go1CHP+wYkuz9W+E8q/rm9/nBO0xutoQhOfV3MxMid69E8i4QjODq3w5mOUrmpj/8gl2FyBU1Ro1xgPSYNEQ4="
